theme: jekyll-theme-leap-day
title: PAYDAY 2 Tradução PT-BR
description: Tradução feita por fãs para fãs
github:
  zip_url: https://github.com/gabsF/payday2_translate_brazilian/releases/download/pd2translationbrazilian/payday2_traducao_pt-br.zip